=== weihuoya/as2lib/trunk/main/changelog.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="as2lib-changelog"
           xmlns="as2lib-changelog"
           elementFormDefault="qualified">
  <xs:element name="changelog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="year">
          <xs:attribute name="count" type="xs:integer" use="required"/>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="month">
                <xs:attribute name="count" type="xs:integer" use="required"/>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="day">
                      <xs:attribute name="count" type="xs:integer" use="required"/>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="entry" type="xs:string">
                            <xs:attribute name="type" type="xs:string" use="required"/>
                            <xs:attribute name="package" type="xs:string" use="optional"/>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== weihuoya/as2lib/trunk/changelog/reader/changelog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  This is a example changelog file to test the functionality of the reader.
  It contains various entries with different content.
-->
<changelog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:noNamespaceSchemaLocation="C:\Dokumente und Einstellungen\main\Desktop\changelog\changelog.xsd">
	<release day="20" month="7" year="2004" name="example">
		<year value="1999">
			<month value="12">
				<day value="11">
					<entry type="change" package="stuff" class="MyClass2" method="myMethod1()">Something changed.</entry>
					<entry type="remove" package="stuff" class="MyClass3" method="myMethod2()">Something removed.</entry>
				</day>
				<!-- Direction test, if its sorted or not -->
				<day value="12">
					<entry type="add">Something added.</entry>
					<entry type="add" package="stuff">Something added.</entry>
					<entry type="add" package="stuff" class="MyClass">Something added.</entry>
					<entry type="add" package="stuff" class="MyClass1" method="myMethod()">Something added.</entry>
				</day>
				<day value="10">
					<entry type="bugfix" package="stuff" class="MyClass4" method="myMethod3()">Some important bug fixed.</entry>
					<entry type="documentation" package="stuff" class="MyClass5" method="myMethod4()">Some documentation changed or added.</entry>
					<entry type="enhancement" package="stuff" class="MyClass6" method="myMethod5()">Enhanced something.</entry>
					<entry type="bugfix" package="stuff" class="MyClass7" method="myMethod6()">Multiline test.
This is some stupid dummie test, lets see what it does.</entry>
				</day>
				<day value="9">
					<entry type="change">More entries with more content</entry>
					<entry type="remove">Another entry.</entry>
					<entry type="remove">Another entry.</entry>
					<entry type="remove">Another entry.</entry>
					<entry type="remove">Another entry.</entry>
					<entry type="remove">Another entry.</entry>
					<entry type="remove">Another entry.</entry>
					<entry type="remove">Another entry.</entry>
				</day>
			</month>
		</year>
	</release>
</changelog>
